name: Build CI

on:
  push:
    paths-ignore:
      - '.github/**'
      - '!**/build_ci.yml'
      - '**/test/**'
      - '**/tests/**'
      - '**/*.md'
      - '**/test_*.v'
      - '**/*_test.v'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!**/build_ci.yml'
      - '**/test/**'
      - '**/tests/**'
      - '**/*.md'
      - '**/test_*.v'
      - '**/*_test.v'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        mode: [debug, dev, release]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true

      - name: Checkout v-analyzer
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: cd tree_sitter_v && npm install

      - name: Build ${{ matrix.mode }}
        run: v run build.vsh ${{ matrix.mode }}

      - name: Check if the build is successful
        run: ./bin/v-analyzer --version
