name: Release Development Version

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/test/**'
      - '**/tests/**'
      - '**/test_*.v'
      - '**/*_test.v'
      - '**/*.md'
      - '.github/**'
      - '!**/nightly_release.yml'

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: windows-x86_64
            bin_ext: .exe
          - os: ubuntu-20.04
            target: linux-x86_64
          - os: macos-latest
            target: darwin-x86_64
          - os: macos-latest
            target: darwin-arm64
            vflags: -d cross_compile_macos_arm64
      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      VFLAGS: ${{ matrix.vflags }}
      ARTIFACT: v-analyzer-${{ matrix.target }}

    steps:
      - name: Install V
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true

      - name: Checkout v-analyzer
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Compile
        run: v run build.vsh debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ./bin/v-analyzer${{ matrix.bin_ext }}

      - name: Prepare release
        shell: bash
        run: |
          now=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
          echo "BODY=Generated on <samp>$now</samp> from commit ${{ github.sha }}." >> $GITHUB_ENV
          7z a -tzip ${{ env.ARTIFACT }}.zip ./bin/v-analyzer${{ matrix.bin_ext }}

      - name: Update nightly tag
        uses: richardsimko/update-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.ARTIFACT }}.zip
          tag: nightly
          body: ${{ env.BODY }}
          name: v-analyzer development build
          prerelease: true
          allowUpdates: true
