name: VS Code Extension CI

on:
  push:
    paths:
      - 'editors/code/**'
      - '**/vscode_extension_tests.yml'
  pull_request:
    paths:
      - 'editors/code/**'
      - '**/vscode_extension_tests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    name: Test VS Code Extension on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout v-analyzer
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd editors/code && npm update

      - name: Run tests
        run: cd editors/code && npm run test
